apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-cloud
spec:
  selector:
    matchLabels:
      app: webmin
      tier: all-cloud
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: webmin
        tier: all-cloud
    spec:
      containers:
      - name: all-cloud
        image: ohanp/webmin:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 10000
