apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
    tier: allcloud
spec:
  type: "{{ .Values.serviceType }}"
  ports:
  - port: 10000
  selector:
    app: demo
    tier: allcloud
