apiVersion: v1
kind: Service
metadata:
  name: webmin
  labels:
    app: testingwebmin
    tier: webmin
spec:
  type: "{{ .Values.serviceType }}"
  ports:
  - port: 10000
  selector:
    app: testingwebmin
    tier: webmin
