namespace: default
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: allcloud
  helm:
    values:
      replicas: 1
  clusterSelector:
    matchLabels:
      env: allcloud

- name: prod
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 3
  clusterSelector:
    matchLabels:
      env: prod
