apiVersion: v1
kind: Service
metadata:
  name: demoweb
  labels:
    app: demoweb
    tier: frontend
spec:
  type: "{{ .Values.serviceType }}"
  ports:
  - port: 8080
  selector:
    app: demoweb
    tier: frontend
