namespace: default
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: jawaapp
  helm:
    values:
      replicas: 1
  clusterSelector:
    matchLabels:
      env: jawaapp

- name: prod
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 1
  clusterSelector:
    matchLabels:
      env: prod
