apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
    tier: jawaapp
spec:
  type: "{{ .Values.serviceType }}"
  ports:
  - port: 80
  selector:
    app: demo
    tier: jawaapp
