apiVersion: v1
kind: Service
metadata:
  name: demowae
  labels:
    app: demowae
    tier: test1
spec:
  type: "{{ .Values.serviceType }}"
  ports:
  - port: 80
  selector:
    app: demowae
    tier: test1
