apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: demoweb
      tier: test
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: demoweb
        tier: test
    spec:
      containers:
      - name: demoweb
        image: adolfintel/speedtest:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
