apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
spec:
  selector:
    matchLabels:
      app: demowae
      tier: test1
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: demowae
        tier: test1
    spec:
      containers:
      - name: demowae
        image: docker.io/15141514/demoweb:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
