apiVersion: v1
kind: Service
metadata:
  name: demoweb
  labels:
    app: demoweb
    tier: test
spec:
  type: "{{ .Values.serviceType }}"
  ports:
  - port: 80
  selector:
    app: demoweb
    tier: test
